sudo: false
language: php
php: 
  - 5.5
  - 5.6
  - 7.0
script: phpunit --coverage-clover build/logs/clover.xml
before_script:
  - composer install --ignore-platform-reqs
after_script:
  - ./vendor/bin/test-reporter
