<?php

return array(
	'css' => array(
		'cms.css.less',
		'editor.css',
	),
	'corejs' => array(
		'boom/helpers.js',
		'jquery/jquery.js',
		'jquery/ui.js',
		'jquery/ui.splitbutton.js',
		'jquery/ui.tree.js',
		'jquery/jgrowl.js',
		'jquery/tablesorter.js',
		'jquery/plugins.js',
		'boom/plugins.js',
		'boom/config.js',
		'boom/loader.js',
		'boom/growl.js',
		'boom/core.js',
		'boom/history.js',
		'boom/log.js',
		'boom/dialog.js',
	),
	'js' => array(
		'boom/menu.js',
		'boom/page/status.js',
		'boom/page.js',
		'boom/page/settings.js',
		'boom/page/editor.js',
		'boom/page/toolbar.js',
		'boom/page/tree.js',
		'boom/page/url.js',
		'boom/urlEditor.js',
		'boom/textEditor.js',
		'boom/wysihtml5.js',
		'boom/chunk/chunk.js',
		'boom/chunk/text.js',
		'boom/chunk/linkset.js',
		'boom/chunk/feature.js',
		'boom/chunk/asset.js',
		'boom/chunk/slideshow.js',
		'boom/chunk/timestamp.js',
		'boom/chunk/tag.js',
		'boom/page/title.js',
		'boom/helpers.js',
		'boom/browser.js',
		'boom/links.js',
		'boom/tags.js',
		'boom/tagAutocompleter.js',
		'jquery/fileupload.js',
		'wysihtml5/wysihtml5x-0.4.2-toolbar.js',
		'wysihtml5/parser_rules.js',
	),
);